version: '3'

services:
#  postgres:
#    container_name: postgres-laborexchange
#    image: postgres
#    environment:
#      POSTGRES_DB: "labor-exchange"
#      POSTGRES_USER: "admin"
#      POSTGRES_PASSWORD: "admin"
#      PGDATA: /data/postgres
#    volumes:
#       - postgres:/data/postgres
#    ports:
#      - "5433:5432"
  postgres_test:
    container_name: postgres-laborexchange-test
    image: postgres
    environment:
      POSTGRES_DB: "labor-exchange"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5434:5432"
volumes:
    postgres: